export const fetchClients = async () => {
//mock
  
    const response = await Promise.resolve({
      success: true,
      data: [
        {
          id: 1,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 2,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 3,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 4,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 5,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 6,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 7,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 8,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 9,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 10,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 11,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 12,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 13,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 14,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 15,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 16,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 17,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 18,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 19,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 20,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 21,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 22,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 23,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 24,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 25,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 26,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 27,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 28,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 29,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 30,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 31,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 32,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 33,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 34,
          partnerName: "Taya",
          domain: "Taya.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 7,
        },
        {
          id: 35,
          partnerName: "test",
          domain: "test.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },
        {
          id: 36,
          partnerName: "test3",
          domain: "test3.quiphire.in",
          activeFlag: false,
          coolOffPeriodDays: 10,
        },

      ],
    });
  
    return response.data;
  };
  